package Assignment2_4;             //Package declaration
import java.util.Arrays;          //Arrays class imported                                                                                                                                                                                                                                                                                                                                                                                        
import java.util.Scanner;         //Scanner class imported                                                                                                                                                                                                                                                                                                                                                                                                     
public class TestDemo {           // Name of the class                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                  
                public static void main(String[] args) {                   //Main method started                                                                                                                                                                                                                                                                                                      
                                Scanner input = new Scanner(System.in);    // object initialized for user input                                                                                                                                                                                                                                                                                                                        
try {                                                                      //exception started                                                                                                                                                                                                                                                                                                                                                                                                                  
                    System.out.print("Enter a number: ");                  //This will print argument at the end of the line                                                                                                                                                                                                                                                                                                             
                    int number = input.nextInt();                          //Integer variable size initialized to get the input from user                                                                                                                                                                                                                                                                                                                        
                    char digit = (char) number;                            //type-casting of "number" to char                                                                                                                                                                                                                                                                                                                                           
                    if( number == 0)                                       // if condition started for "number is zero"                                                           
                                { System.out.println("You Have Entered Zero");                                                                                                                                                                                                                                                                                
                                String text1 = Integer.toString(number);         //type-casting from integer to string     
                                byte[] bytes1 = text1.getBytes("US-ASCII");      //type-casting from byte to text  
                                System.out.print ("The ASCII representation of " + number + " is "); System.out.print(Arrays.toString(bytes1));
                        }                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                    else if (number > 0)                                          // if condition started for "number is greater than zero"                                                                                                                                                                                                                                                                                                                                          
                                { System.out.println("You Have Entered Positive Value");                                                                                                                                                                                                                             
                                  System.out.println("The ASCII representation of " + number + " is " + digit + "");                                                                                                             
                        }                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                    else                                                          //condition started for "number is less than zero"                                                                                                                                                                                                                                                                                                                                                                                          
                       { System.out.println("You Have Entered Negative Value");                                                                                                                                                                                                                   
                                String text = Integer.toString(number);                                                                                                                                                                                                                                                                                                 
                                byte[] bytes = text.getBytes("US-ASCII");                                                                                                                                                                                                                                                                                            
                                System.out.print ("The ASCII representation of " + number + " is "); System.out.print(Arrays.toString(bytes));            
                       }                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                } catch (java.io.UnsupportedEncodingException e){                 //It will handle exception if the condition is out of scope.                                                                                                                                                                                                                                                                       
      e.printStackTrace();}                                                                                                                                                                                                                                                                                                                                                                                                
                input.close();                                                                                                                                                                                                                                                                                                                                                                                                                                     
                }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
}                                       